export default [
    {
        id: 8,
        fullImg: "assets/images/rocks5.jpg",
        img: "assets/images/rocks5.jpg",
        title: "Golden Pyrite",
        description: "This was found in the fields of Mordor. Taken after the great battle.",
    },
    {
        id: 7,
        fullImg: "assets/images/rocks6.jpg",
        img: "assets/images/rocks6.jpg",
        title: "Lorem ipsum dolor sit",
        description: "2 Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
        {
        id: 6,
        fullImg: "assets/images/rocks3.jpg",
        img: "assets/images/rocks3.jpg",
        title: "Borem ipsum dolor sit",
        description: "3 Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
        {
        id: 5,
        fullImg: "assets/images/rocks8.jpg",
        img: "assets/images/rocks8.jpg",
        title: "Zorem ipsum dolor sit",
        description: "4 Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
        {
        id: 4,
        fullImg: "assets/images/rocks1.jpg",
        img: "assets/images/rocks1.jpg",
        title: "Norem ipsum dolor sit",
        description: "5 Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
        {
        id: 3,
        fullImg: "assets/images/rocks5.jpg",
        img: "assets/images/rocks5.jpg",
        title: "Porem ipsum dolor sit",
        description: "6 Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
        {
        id: 2,
        fullImg: "assets/images/rocks3.jpg",
        img: "assets/images/rocks3.jpg",
        title: "Jorem ipsum dolor sit",
        description: "7 Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
        {
        id: 1,
        fullImg: "assets/images/rocks4.jpg",
        img: "assets/images/rocks4.jpg",
        title: "Orem ipsum dolor sit",
        description: "8 Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
]